Lab3
UlyanaBend/BelBasketSo pull request #5
Opened 2021-03-02 07:13 UTC by UlyanaBend

2021-03-13 16:54 UTC, VeronikaYastr requested changes

2021-03-13 16:54 UTC, VeronikaYastr commented on sql/text.txt
> +    name VARCHAR(20) NOT NULL default 0,
я бы сделала больше символов на имя и фамилию (50 хотя бы)
default 0 не знаю зачем тут тебе, это строки и они не могут быть пустыми никак (даже если бы могли, то default "" тогда уже)

2021-03-13 16:54 UTC, VeronikaYastr commented on sql/text.txt
> +    email VARCHAR(30) NOT NULL default 0,
тоже лучше больше символов. default 0 везде лучше убрать, кроме поля likes в таблице post

2021-03-13 16:54 UTC, VeronikaYastr commented on sql/text.txt
> +    modified_at DATE,
тоже лучше not null, обычно при создании она сетится в текущую дату и потом уже обновляется в случае изменений

2021-03-13 16:54 UTC, VeronikaYastr commented on sql/text.txt
> +    erro_message VARCHAR(50) NOT NULL default 0,
опечатка - error_message

2021-03-15 11:50 UTC, UlyanaBend commented on sql/text.txt
> +    erro_message VARCHAR(50) NOT NULL default 0,
вроде, все исправила

2021-03-17 14:37 UTC, merged